version: 2
updates:
    - package-ecosystem: "composer"
      directory: "/"
      open-pull-requests-limit: 10
      assignees:
          - "Julien-Broyard"
      schedule:
          interval: "daily"
