knp_paginator:
    default_options:
        distinct: true
        filter_field_name: filterField
        filter_value_name: filterValue
        page_name: page
        sort_direction_name: direction
        sort_field_name: sort
    page_range: 2
    template:
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'
        pagination: 'themes/bulma_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'