parameters:
    picterest_email: 'picterest@no-reply.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $imageDir: "%kernel.project_dir%/public/uploads/images"

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_URL)%'
