name: Code style, static analysis and tests

on:
    pull_request:
    push:
        branches: [master]

jobs:
    ci:
        name: ci
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'

            -   name: Install Dependencies
                run: composer install --no-progress --no-interaction --prefer-dist

            -   name: Run Formatting Script
                run: make format

            -   name: Run Linting Script
                run: make lint

